### ISSUE TITLE
Works great.. can we add pictures ? 

### ISSUE THREAD

**Issue by johncohn** [gurbaaz27/linkedin-comments-scraper#2]
Just used your code and it worked great. How hard would it be to also pull pictures that people included in their comments. Sam question for the posters profile picture ? THanks for building this. I'd love to help wiht the add tof these features if I can

**Comment by gurbaaz27** [comment]
Hi John,
Thanks for the compliment and feedback :)
I was also thinking about profile pictures when I made this project year ago, so I now just added the support for it! You may go ahead and pull the latest changes, and use `--downloadpfp` flag in `python main.py` for it (README has been updated with details). Even if the flag isn't provided, URLs of image would get stored in the output csv.

I can also add support for pulling pictures in comments, or if you want to, you may go ahead and make a PR for it. (You may see how I added profile picture support)
